- name: poll the haproxy site
  wait_for: host=0.0.0.0 port=80 timeout=15

- command: rm -f index.html

- command: wget -O index.html http://0.0.0.0:80

- name: capture the output file comment
  command: cat index.html
  register: result

- name: fail when the result content
  fail: "could not verify nginx"
  when: '"This is me on nginx container" not in result.stdout'

